"""update_request_log_schema

Revision ID: 101cc58732b5
Revises: 
Create Date: 2026-03-15 10:54:51.865955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101cc58732b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('method', sa.String(), nullable=True))
    op.alter_column('request_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('request_logs', 'method')
    # ### end Alembic commands ###
