"""update user role default and request_log status_code

Revision ID: c60221957020
Revises: 101cc58732b5
Create Date: 2026-03-15 12:04:45.291028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60221957020'
down_revision: Union[str, Sequence[str], None] = '101cc58732b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column allowing NULLs
    op.add_column('request_logs', sa.Column('status_code', sa.Integer(), nullable=True))

    # 2. Fill existing rows with a default value (e.g., 200)
    op.execute("UPDATE request_logs SET status_code = 200")

    # 3. Now change it to NOT NULL
    op.alter_column('request_logs', 'status_code', nullable=False)
    op.drop_column('request_logs', 'status')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('request_logs', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('request_logs', 'status_code')
    # ### end Alembic commands ###
